#!/bin/bash
# LiteLLM 配置文件生成器
# 根据 CloudFormation 参数动态生成 litellm_config.yaml

set -euo pipefail

OUTPUT_FILE="${1:-/etc/litellm/config.yaml}"
MODEL_ID="${2:-global.amazon.nova-2-lite-v1:0}"
MONTHLY_BUDGET="${3:-50}"
GUARDRAIL_ID="${4:-}"
ENABLE_CACHE="${5:-true}"

# 解析模型 ID 提取模型名称和提供商
parse_model() {
    local model_id="$1"
    local model_name=""
    local provider=""
    
    if [[ "$model_id" == *"amazon"* ]]; then
        provider="bedrock"
        model_name="$model_id"
    elif [[ "$model_id" == *"anthropic"* ]]; then
        provider="bedrock"
        model_name="$model_id"
    elif [[ "$model_id" == *"meta"* ]]; then
        provider="bedrock"
        model_name="$model_id"
    elif [[ "$model_id" == *"deepseek"* ]]; then
        provider="bedrock"
        model_name="$model_id"
    else
        # 默认 Bedrock
        provider="bedrock"
        model_name="$model_id"
    fi
    
    echo "$provider/$model_name"
}

# 生成预算告警配置
generate_budget_config() {
    local budget="$1"
    cat <<EOF
  budget_alerts:
    - budget: ${budget}
      frequency: monthly
      alert_threshold: 0.8
      alert_type: slack  # 可改为 webhook
EOF
}

# 生成 Guardrails 配置
generate_guardrails_config() {
    local guardrail_id="$1"
    if [[ -n "$guardrail_id" && "$guardrail_id" != "" ]]; then
        cat <<EOF
  guardrails:
    - id: ${guardrail_id}
      type: bedrock
      enabled: true
EOF
    fi
}

# 生成缓存配置
generate_cache_config() {
    local enable_cache="$1"
    if [[ "$enable_cache" == "true" ]]; then
        cat <<EOF
  cache:
    type: redis
    host: localhost
    port: 6379
    ttl: 3600  # 1 小时缓存
    semantic_cache: true
    similarity_threshold: 0.9
EOF
    else
        cat <<EOF
  cache:
    enabled: false
EOF
    fi
}

# 主模型路由配置
generate_model_config() {
    local parsed_model
    parsed_model=$(parse_model "$MODEL_ID")
    
    cat <<EOF
model_list:
  - model_name: default
    litellm_params:
      model: ${parsed_model}
      region_name: us-west-2
      max_retries: 3
      timeout: 60
EOF
}

# 智能路由策略（多模型 fallback）
generate_routing_rules() {
    cat <<EOF
router_settings:
  routing_strategy: simple-shuffle
  fallbacks:
    - models: ["${MODEL_ID}"]
      fallback_models:
        - bedrock/global.amazon.nova-lite-v1:0
        - bedrock/anthropic.claude-3-haiku-20240307-v1:0
  allowed_fails: 3
  cooldown_time: 60
EOF
}

# 生成完整的配置文件
cat > "$OUTPUT_FILE" <<EOF
# LiteLLM Configuration
# Generated by OpenClaw Enterprise Bootstrap Script
# Model: ${MODEL_ID}
# Budget: \$${MONTHLY_BUDGET}/month
# Guardrails: ${GUARDRAIL_ID:-None}
# Cache: ${ENABLE_CACHE}

general_settings:
  master_key: sk-litellm-openclaw-enterprise
  database_url: null  # 可选：启用数据库跟踪用量
  
$(generate_model_config)

$(generate_routing_rules)

$(generate_cache_config)

litellm_settings:
  drop_params: true
  set_verbose: false
  telemetry: false
  
$(generate_budget_config "$MONTHLY_BUDGET")

$(generate_guardrails_config "$GUARDRAIL_ID")

environment_variables:
  AWS_REGION: us-west-2
  LITELLM_LOG_LEVEL: INFO
EOF

echo "✅ LiteLLM config generated: $OUTPUT_FILE"
echo "   Model: $MODEL_ID"
echo "   Budget: \$$MONTHLY_BUDGET/month"
if [[ -n "$GUARDRAIL_ID" && "$GUARDRAIL_ID" != "" ]]; then
    echo "   Guardrails: $GUARDRAIL_ID"
fi
echo "   Cache: $ENABLE_CACHE"
